### ISSUE TITLE
Final v0.21 Release Audit Checklist

### ISSUE THREAD

**Issue by matthewp** [snowpackjs/astro#1905]
Go through the examples and test that they are working against `next`

# Dev

* [x] blog-multiple-authors
* [x] blog
* [x] docs
* [x] framework-lit
* [x] framework-multiple
* [x] framework-preact (@drwpow)
* [x] framework-react (@drwpow)
* [x] framework-solid
* [x] framework-svelte
* [x] framework-vue
* [x] minimal
* [x] portfolio-svelte (mp)
* [x] portfolio (mp)
* [x] starter
* [x] subpath (mp)
* [x] with-markdown-plugins (@natemoo-re)
* [x] with-markdown (@natemoo-re)
* [x] with-nanostores (@jonathantneal)
* [x] with-tailwindcss

# Built

* [x] blog-multiple-authors
* [x] blog
* [x] docs
* [x] framework-lit
* [x] framework-multiple
* [x] framework-preact (@drwpow)
* [x] framework-react (@drwpow)
* [x] framework-solid (@drwpow)
* [x] framework-svelte
* [x] framework-vue
* [x] minimal
* [x] portfolio-svelte (mp)
* [x] portfolio (mp)
* [x] starter
* [x] subpath (mp)
* [x] with-markdown-plugins (@natemoo-re)
* [x] with-markdown (@natemoo-re)
* [x] with-nanostores (@jonathantneal)
* [x] with-tailwindcss

# Release Items
* [x] Clean up `.changeset` to reflect a full summary of what has changed! 
    * Audit `patch/minor` tags
    * feel free to copy from (and link to) new release blog post if it would take too long to write from scratch (we can come back to improve this later)
